### ISSUE TITLE
Header Section :  Social links are not navigating to their respective pages

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#1]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![header_social_1](https://cloud.githubusercontent.com/assets/13309806/8796755/105f7ea0-2f4c-11e5-91c8-39fb38122637.png)

**Comment by masi-titan** [comment]
Dev: Linked in social link not provided

**Comment by ravi-josyula** [comment]
QA: As per the provided prototype Linked in social link should be implemented

**Comment by ravi-josyula** [comment]
QA : As per the provided prototype Linked in social link should be implemented
