### ISSUE TITLE
Testimonials page : Unnecessary space is occurring

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#101]
![testimonials_0001](https://cloud.githubusercontent.com/assets/13309806/9053984/d90b2ab6-3a28-11e5-94be-5454eb485958.png)

**Comment by maehtitan** [comment]
Highlighted space still not the same on the rest of the testimonial content spaces

![image](https://cloud.githubusercontent.com/assets/13363508/9057020/92094b24-3ac9-11e5-8ca3-44942877c659.png)
