### ISSUE TITLE
Banner Section : Banner image is too large 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#12]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![banner_1](https://cloud.githubusercontent.com/assets/13309806/8797296/4f669838-2f4f-11e5-81e8-8631b0da89a6.png)

**Comment by masi-titan** [comment]
Dev: it is appearing as per our screen and it is not a banner its a background image
