### ISSUE TITLE
Banner Section : Tool tip is not changing when banner is rotating

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#16]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![banner_5](https://cloud.githubusercontent.com/assets/13309806/8797490/9e814ce6-2f50-11e5-8cad-c1805312e2a7.png)

**Comment by masi-titan** [comment]
Dev: it is changing while rotating banner please refresh and review
