### ISSUE TITLE
Footer section	 : Alignment is not implemented as per the given prototype

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#18]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![footer_section_3](https://cloud.githubusercontent.com/assets/13309806/8797544/fbe58852-2f50-11e5-8b05-e47a2c14afed.png)

**Comment by ravi-josyula** [comment]
Issue is not fixed

**Comment by maehtitan** [comment]
Not yet fixed in Contact Us page
