### ISSUE TITLE
Home Page : Welcome content section is out of the banner

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#22]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![home_page_2](https://cloud.githubusercontent.com/assets/13309806/8797906/8c94e508-2f53-11e5-86d0-74d2875efb45.png)

**Comment by masi-titan** [comment]
Dev: its not out of banner its a background image with limited dummy content on homepage but I have implemented web content as per web copy  provided
