### ISSUE TITLE
Services & Prices Page: 	Banner alignment is distorting (Banner should touch the Footer section) as per provided prototype

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#41]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![services_prices_2](https://cloud.githubusercontent.com/assets/13309806/8798572/17dec4b8-2f58-11e5-9890-7ff59b1361e1.png)

**Comment by masi-titan** [comment]
Not a bug not fix
