### ISSUE TITLE
Services & Prices Page	: Unnecessary space is occurring below footer, applicable for gallery page also

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#47]
Devices : I pad(P & L)

![services_prices_ipad_1](https://cloud.githubusercontent.com/assets/13309806/8798719/3ecf7aa8-2f59-11e5-891a-646ef54755a5.png)

**Comment by ravi-josyula** [comment]
Still issue is not fixed in gallery page (Mozilla firefox)
Devices: IPad(mini), Ipad

![gallery](https://cloud.githubusercontent.com/assets/13309806/9032668/5d8886ce-396d-11e5-9b75-21ddb8d4d1b5.png)

**Comment by masi-titan** [comment]
Dev: its not a bug
