### ISSUE TITLE
Header Section : Social links and Menu Link Breaks to the next line at 320, 360 and 480 resolutions

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#5]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![header_social_menu_4](https://cloud.githubusercontent.com/assets/13309806/8797017/c2f37cbe-2f4d-11e5-96c0-9e62b99f548f.png)

**Comment by masi-titan** [comment]
Dev: 480 X 320 port we are showing Social Links and Menu down in 1 column
