### ISSUE TITLE
Contact Us page : As per given launch list address to be complete with state and postcode written in full

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#70]
Browsers : Mozilla39, Chrome43, Opera30, IE9, Safari5

![contact-us_page_4](https://cloud.githubusercontent.com/assets/13309806/8799325/2fe06e62-2f5e-11e5-8aad-347435cc8782.png)

**Comment by masi-titan** [comment]
As per the design its 'WA', however this should not be marked as bug.

**Comment by ravi-josyula** [comment]
When I'm testing WA is not capitalized and address is not complete, but now its fixed.
