### ISSUE TITLE
Header section : Facebook social link alignment is out of layout and Menu is overlapping with lead-ins at 480 resolution

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Road-Rules-Driving-School#97]
Browser : Safari

![header_safari-001](https://cloud.githubusercontent.com/assets/13309806/9053891/ad968f16-3a27-11e5-8f8d-97d610579f43.png)

**Comment by maehtitan** [comment]
Not yet fixed, still overlapped at the moment
